version: "3.6"
services:
  mysql1:
     image: mysql5.6
     container_name: mysql1
       
     networks:
       mysqlnet:
         ipv4_address: 192.168.16.11
     ports:
       - "13307:3306"
     expose:
       - 3306
     tty: true
     privileged: true
     command: /etc/init.d/mysql start
  mysql2:
     image: mysql5.6
     container_name: mysql2
     networks:
       mysqlnet:
         ipv4_address: 192.168.16.12
     ports:
       - "13308:3306"
     expose:
       - 3306
     tty: true
     privileged: true
     command: /etc/init.d/mysql start
  mysql3:
     image: mysql5.6
     container_name: mysql3
     networks:
       mysqlnet:
         ipv4_address: 192.168.16.13
     ports:
       - "13309:3306"
     expose:
       - 3306
     tty: true
     privileged: true
     command: /etc/init.d/mysql start     

networks:
  mysqlnet:
     external:
      name: mysqlnet